import './globals.css'


export const metadata = {
  title: 'NextJS App Router',
  description: 'Generated by nextJS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='min-h-screen text-4xl'>
          {children}
        </div>
      </body>
    </html>
  )
}
