import './globals.css'

export const metadata = {
  title: 'NextJS App Router',
  description: 'Generated by nextJS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>Header</header>
      <body>{children}</body>
      <footer>Footer</footer>
    </html>
  )
}
