import Navbar from '@/components/shared/Navbar'
import './globals.css'
import Footer from '@/components/shared/Footer'

export const metadata = {
  title: 'NextJS App Router',
  description: 'Generated by nextJS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <div className='min-h-screen'>
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  )
}
