import Sidebar from "@/components/shared/Sidebar";

export const metadata = {
    title: 'NextJS Dashboard',
    description: 'Generated by nextJS',
}

const DashboardLayout = ({ children }) => {
    return (
        <div className="flex">
            <Sidebar />
            <div className="w-full">
                {children}
            </div>
        </div>
    );
};

export default DashboardLayout;